project:
  type: website

website:
  title: "michaeldismorrmd.github.io"
  site-url: https://michaeldismorrmd.github.io
  repo-url: https://github.com/MichaelDismorrMD/michaeldismorrmd.github.io
  repo-actions: [edit, issue]
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: blog_start.qmd
        text: Blog
      - href: guides/guides.qmd
        text: Guides
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/MichaelDismorrMD/michaeldismorrmd.github.io
          - text: Report a Bug
            href:  https://github.com/MichaelDismorrMD/michaeldismorrmd.github.io/issues/new
            
  sidebar:
    - title: Guides
      style: "docked"
      background: light
      contents: 
        - section: Guides
          contents: 
            - guides/guides.qmd
        - section: "Setup Guide"
          contents: 
            - guides/setup/setup_1.qmd
            - guides/setup/setup_2.qmd
            - guides/setup/setup_3.qmd
            - guides/setup/setup_4.qmd
            - guides/setup/setup_5.qmd
            - guides/setup/setup_6.qmd
        - section: "New project"
          contents: 
            - guides/new_project/new_project_1.qmd
            - guides/new_project/new_project_2.qmd
        - section: "Collaborate"
          contents: 
            - guides/collaborate/collaborate_1.qmd
            - guides/collaborate/collaborate_2.qmd
            - guides/collaborate/collaborate_3.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



