project:
  type: website

website:
  title: "michaeldismorrmd.github.io"
  site-url: https://michaeldismorrmd.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: blog_start.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



