project:
  type: website

website:
  title: "michaeldismorrmd.github.io"
  site-url: https://michaeldismorrmd.github.io
  repo-url: https://github.com/MichaelDismorrMD/michaeldismorrmd.github.io
  repo-actions: [edit, issue]
  search: 
    location: navbar
    type: overlay
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: blog_start.qmd
        text: Blog
      - href: setup_guide/setup_1.qmd
        text: Setup guide
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/MichaelDismorrMD/michaeldismorrmd.github.io
          - text: Report a Bug
            href:  https://github.com/MichaelDismorrMD/michaeldismorrmd.github.io/issues/new
            
  sidebar:
    - title: "Setup guide"
      style: "docked"
      background: light
      contents:
        - setup_guide/setup_1.qmd
        - setup_guide/setup_2.qmd
        - setup_guide/setup_3.qmd
        - setup_guide/setup_4.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



