{
  "hash": "4d28dfb106167c2ed281e78bc752495a",
  "result": {
    "markdown": "---\ntitle: \"Age-, and sex-adjusted incidence rates\"\nauthor: \"Michael Dismorr\"\ndate: \"2021-11-15\"\ndate-modified: \"2024-06-01\"\ncategories: [R, incidence-rate, poisson-regression, survival-analysis]\n---\n\n\nIn this first post I'm going to present a way of obtaining age- and sex-adjusted incidence rates using poisson regression in R. This will be similar to what is done in Stata as described [here](https://www.statalist.org/forums/forum/general-stata-discussion/general/1431921-age-adjusted-rates-using-a-poisson-regression).\n\nI've written a R function that's available for download [here.](age_sex_adjust.R) The script can be sourced ( `source(\"age_sex_adjust.R\")` ) and then the function `age_sex_adjust()` can be used as is. Note that the time variable will have to be in days, and the incidence will be presented as per 100 person-years. The code will also be described step by step below.\n\n***\n\nThere are, as usual, several ways to calculate adjusted incidence rates in R. I've chosen to use the package [marginaleffects](https://marginaleffects.com) by [Vincent Arel-Bundock, ](https://x.com/vincentab) Noah Greifer and Andrew Heiss because it has a lot of nice features and useful implications in causal inference. Specifically, we will use the function `avg_predictions()` from `marginaleffects` to generate the the adjusted incidence rates. \n\n\nBut first we start off with a little bit of background on what an incidence rate is. It is simply a measure of a number of occurrences (a count) in a population over the total population time. For example, in a population of 10 people, each followed 1 year, there was one case of death. In that population, the incidence rate of death would 1 per 10 person-years. In observational data, we often have larger cohorts with varying follow-up time and censoring.  The calculation is of course the same, using the formula below:   \n<br>\n$$\\text{Incidence rate} = \\frac{\\text{Number of occurrences}}{\\sum_{\\text{Persons}}{\\text{Time in study}}}$$\n<br>\n  \n\n***\n\n### Calculating crude incidence rate  \n\nTo illustrate, we will now use the `colon` dataset from the `survival` package. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\nlibrary(dplyr)\nlibrary(broom)\n```\n:::\n\n\nRunning `?survival::colon` tells us the following:\n\n> Data from one of the first successful trials of adjuvant chemotherapy for colon cancer  \n\nVariable | Explanation\n-------- | -----------\nid | Patient id\nstudy | 1 for all patients\nrx | 1 for all patients\nsex | 1 = male  \nage | in years  \nobstruct |colon obstruction by tumour  \nperfor | performation of colon  \nadhere | adherence to nearby organs  \nnodes | number of positive lymph nodes  \ntime | days until event or censoring  \nstatus | censoring status  \ndiffer | tumour differentiation --- 1 = well, 2 = moderate, 3 = poor  \nextent | extent of local spread --- 1 = submucosa, 2 = muscle, 3 = serosa, 4 = continious  \nsurg | time from surgery to registration --- 0 = short, 1 = long  \nnode4 | more than 4 positive lymph nodes  \netype | event type --- 1 = recurrence, 2 = death  \n\nOK, so now that we understand the data, let's start calculating crude incidence rates for death among the different treatment groups:    \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Using the colon dataset from the survival package\n\n# Only keep records related to the death outcome\ncolon_death <- survival::colon %>% dplyr::filter(etype == 2) \n\n# Time is divided by 365.25/100 to get the time in days \n# first to years, then to 100 person-years\n\ncolon_death %>% group_by(rx) %>% \n                summarise(Events = sum(status), \n                          Time = sum(time/365.25/100), \n                          Rate = Events / Time, \n                          lower = poisson.test(Events, Time)$conf.int[1], \n                          upper = poisson.test(Events, Time)$conf.int[2])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 6\n  rx      Events  Time  Rate lower upper\n  <fct>    <dbl> <dbl> <dbl> <dbl> <dbl>\n1 Obs        168  13.8 12.2  10.4  14.2 \n2 Lev        161  13.7 11.7  10.0  13.7 \n3 Lev+5FU    123  15.0  8.22  6.83  9.80\n```\n:::\n:::\n\nNow we compare to the calculated rates with rates obtained from the `survRate()` function from the [biostat3](https://cran.r-project.org/package=biostat3) package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(biostat3)\nsurvRate(Surv(time/365.25/100, status) ~ rx, data = colon_death) %>% \n  dplyr::select(rx, event, tstop, rate, lower, upper) %>% \n  as_tibble() %>% \n  dplyr::rename(Events = event, \n                Time = tstop, \n                Rate = rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 6\n  rx      Events  Time  Rate lower upper\n  <fct>    <dbl> <dbl> <dbl> <dbl> <dbl>\n1 Obs        168  13.8 12.2  10.4  14.2 \n2 Lev        161  13.7 11.7  10.0  13.7 \n3 Lev+5FU    123  15.0  8.22  6.83  9.80\n```\n:::\n:::\n\n  \nGood, the incidence rates are identical. The observational patients had an mortality incidence rate of 12.2 per 100 person-years, compared to the Lev+5-FU treated patients with an incidence rate of 8.22 per 100 person-years. Now, let's try and repeat these results with poisson regression. \n\n\n### Obtaining estimated incidence rates using poisson regression\n\nHere we use the [broom](https://broom.tidymodels.org/) package `tidy()` function to obtain exponentiated estimates:\n  \n  \n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit the model to estimate IRR using offset\npoisson_fit <- glm(status ~ rx + offset(log(time/365.25/100)), \n                   family = poisson, data = colon_death)\n\n# Exponentiate the estimate to obtain IRR\ntidy(poisson_fit, exponentiate = T, conf.int = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 7\n  term        estimate std.error statistic   p.value conf.low conf.high\n  <chr>          <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n1 (Intercept)   12.2      0.0772    32.4   3.13e-230   10.4      14.1  \n2 rxLev          0.965    0.110     -0.324 7.46e-  1    0.777     1.20 \n3 rxLev+5FU      0.675    0.119     -3.32  9.16e-  4    0.534     0.850\n```\n:::\n:::\n\nThe Intercept estimate here is the estimated IR for the reference level, i.e. the Obs group. \n\nTo get estimated IR of Lev+5FU treated:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlev_5fu <- predict(poisson_fit, \n                   newdata = data.frame(rx = \"Lev+5FU\", time = 36525), \n                   type = \"link\", se.fit = T)\n\nas_tibble(lev_5fu) %>% summarise(Treatment = \"Lev+5FU\", \n                                 IR = exp(fit), \n                                 lower = exp(fit - (1.96 * se.fit)), \n                                 upper = exp(fit + (1.96 * se.fit)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 4\n  Treatment    IR lower upper\n  <chr>     <dbl> <dbl> <dbl>\n1 Lev+5FU    8.22  6.88  9.80\n```\n:::\n:::\n\nHere, the confidence interval needs to be calculated on the $\\log$ scale and then exponentiated back. This will cause the confidence interval to not be centered around the estimate.  \n\nA poisson model can model $\\log\\text{incidence rates (ratios)}$ when we use the time variable as an offset. Therefore, we can include covariates in the model to be accounted for, such as age and sex.\n\n### Age- and sex-adjusted incidence rates using poisson regression\n\nFirst, we'll do it using my `age_sex_adjust()` function\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"age_sex_adjust.R\")\n# Usage: age_sex_adjust(data, group, age, sex, event, time)\n\nage_sex_adjust(colon_death, rx, age, sex, status, time)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Treatment        IR  Lower_CI  Upper_CI\n1   Lev+5FU  8.245483  6.786784  9.704182\n2       Obs 12.211861 10.362612 14.061109\n3       Lev 11.819634  9.990691 13.648577\n```\n:::\n:::\n\nHere we see that the adjusted rates are very similar to the crude rates calculated above. Since this data comes from a randomized trial, this is expected and can be taken as a sign that the randomization worked.  \n\nNow, let's do the some thing but without using the ready made function to see how it works under the hood. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(marginaleffects)\n\n# Fit the model using offset to estimate IRR\npoisson_fit <- glm(status ~ rx * I(age^2) + sex + offset(log(as.numeric(time))), \n                   data = colon_death, \n                   family = poisson)\n\n# Create a new dataset where time is converted to 36525 days (100 years)\nnewdat <- colon_death %>% mutate(time = 36525) \n\n# Use avg_predictions to estimate what the incidence rate would have been if \n# the entire population would have been treated according to each level of rx\nresult <- avg_predictions(poisson_fit, \n                          variables = \"rx\", \n                          newdata = transform(colon_death, time = 36525), \n                          type = \"response\")\n\nresult %>% dplyr::select(rx, estimate, conf.low, conf.high)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Estimate CI low CI high\n     8.25   6.79     9.7\n    12.21  10.36    14.1\n    11.82   9.99    13.6\n\nColumns: rx, estimate, conf.low, conf.high \n```\n:::\n:::\n\nThe numbers are identical to the ones obtained from the `age_sex_adjust()` function, which is logical since we did the same thing as the function does.  \nA few finishing notes. Here I included age as a quadratic term, and as an interaction with exposure. These are modeling decisions one will have to take, however the model could have been only a main effects model such as:  \n<br>\n$$\\log\\lambda = \\beta_0 + \\beta_1\\text{rxLev} + \\beta_2\\text{rxLev+5FU} + \\beta_3\\text{age} + \\beta_4\\text{sex}$$ \n<br>\nRegarding the interaction term, a good explanation was given in the Stata forum in [this](https://www.statalist.org/forums/forum/general-stata-discussion/general/1431921-age-adjusted-rates-using-a-poisson-regression) post.  \n\nFor anyone who wants to read more, I recommend the course material from the PhD course **Biostatistics III** at Karolinska Institutet, available [here](https://biostat3.net).  \n\n\n\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}